urls:
  - 01, https://docs.fireworks.ai/getting-started/introduction
  - 02, https://docs.fireworks.ai/getting-started/quickstart
  - 03, https://docs.fireworks.ai/getting-started/concepts
  - 04, https://docs.fireworks.ai/guides/querying-text-models
  - 05, https://docs.fireworks.ai/guides/querying-vision-language-models
  - 06, https://docs.fireworks.ai/guides/querying-embeddings-models
  - 07, https://docs.fireworks.ai/guides/function-calling
  - 08, https://docs.fireworks.ai/structured-responses/structured-output-grammar-based
  - 09, https://docs.fireworks.ai/structured-responses/structured-response-formatting
  - 10, https://docs.fireworks.ai/guides/prompt-caching
  - 11, https://docs.fireworks.ai/models/overview
  - 12, https://docs.fireworks.ai/models/uploading-custom-models
  - 13, https://docs.fireworks.ai/fine-tuning/fine-tuning-models
  - 14, https://docs.fireworks.ai/fine-tuning/fine-tuning-via-api
  - 15, https://docs.fireworks.ai/guides/lora-model-merge
  - 16, https://docs.fireworks.ai/models/deploying
  - 17, https://docs.fireworks.ai/models/quantization
  - 18, https://docs.fireworks.ai/guides/ondemand-deployments
  - 19, https://docs.fireworks.ai/deployments/regions
  - 20, https://docs.fireworks.ai/deployments/reservations
  - 21, https://docs.fireworks.ai/deployments/direct-routing
  - 22, https://docs.fireworks.ai/guides/server-apps-quickstart
  - 23, https://docs.fireworks.ai/guides/server-apps
  - 24, https://docs.fireworks.ai/guides/quotas_usage/rate-limits
  - 25, https://docs.fireworks.ai/accounts/users
  - 26, https://docs.fireworks.ai/accounts/sso
  - 27, https://docs.fireworks.ai/guides/security_compliance/data_handling
  - 28, https://docs.fireworks.ai/troubleshooting/status_error_codes/inference_error_code
  - 31, https://docs.fireworks.ai/api-reference/introduction
  - 32, https://docs.fireworks.ai/api-reference/post-chatcompletions
  - 33, https://docs.fireworks.ai/api-reference/post-completions
  - 34, https://docs.fireworks.ai/api-reference/creates-an-embedding-vector-representing-the-input-text
  - 35, https://docs.fireworks.ai/api-reference/generate-a-new-image-from-a-text-prompt
  - 36, https://docs.fireworks.ai/api-reference/audio-transcriptions
  - 37, https://docs.fireworks.ai/api-reference/audio-translations
  - 38, https://docs.fireworks.ai/api-reference/audio-alignments
  - 39, https://docs.fireworks.ai/api-reference/audio-realtime-transcriptions
  - 40, https://docs.fireworks.ai/api-reference/get-account
  - 41, https://docs.fireworks.ai/api-reference/list-deployments
  - 42, https://docs.fireworks.ai/api-reference/get-deployment
  - 43, https://docs.fireworks.ai/api-reference/create-deployment
  - 44, https://docs.fireworks.ai/api-reference/update-deployment
  - 45, https://docs.fireworks.ai/api-reference/delete-deployment
  - 46, https://docs.fireworks.ai/api-reference/create-deployed-model
  - 47, https://docs.fireworks.ai/api-reference/delete-deployed-model
  - 48, https://docs.fireworks.ai/api-reference/list-models
  - 49, https://docs.fireworks.ai/api-reference/get-model
  - 50, https://docs.fireworks.ai/api-reference/create-model
  - 51, https://docs.fireworks.ai/api-reference/update-model
  - 52, https://docs.fireworks.ai/api-reference/delete-model
  - 53, https://docs.fireworks.ai/api-reference/get-model-upload-endpoint
  - 54, https://docs.fireworks.ai/api-reference/get-model-download-endpoint
  - 55, https://docs.fireworks.ai/api-reference/validate-model-upload
  - 56, https://docs.fireworks.ai/api-reference/list-users
  - 57, https://docs.fireworks.ai/api-reference/get-user
  - 58, https://docs.fireworks.ai/api-reference/create-user
  - 59, https://docs.fireworks.ai/api-reference/update-user
  - 60, https://docs.fireworks.ai/api-reference/list-datasets
  - 61, https://docs.fireworks.ai/api-reference/get-dataset
  - 62, https://docs.fireworks.ai/api-reference/create-dataset
  - 63, https://docs.fireworks.ai/api-reference/upload-dataset-files
  - 64, https://docs.fireworks.ai/api-reference/get-dataset-upload-endpoint
  - 65, https://docs.fireworks.ai/api-reference/validate-dataset-upload
  - 66, https://docs.fireworks.ai/api-reference/update-dataset
  - 67, https://docs.fireworks.ai/api-reference/delete-dataset
  - 68, https://docs.fireworks.ai/api-reference/list-fine-tuning-jobs
  - 69, https://docs.fireworks.ai/api-reference/get-fine-tuning-job
  - 70, https://docs.fireworks.ai/api-reference/create-fine-tuning-job
  - 71, https://docs.fireworks.ai/api-reference/update-fine-tuning-job
  - 72, https://docs.fireworks.ai/api-reference/delete-fine-tuning-job
  - 73, https://docs.fireworks.ai/cookbook/cookbook_landing
  - 74, https://docs.fireworks.ai/cookbook/learn_with_fireworks/ecosystem_examples
  - 75, https://docs.fireworks.ai/cookbook/projects_showcase/community_examples
  - 76, https://docs.fireworks.ai/tools-sdks/firectl/firectl
  - 77, https://docs.fireworks.ai/tools-sdks/firectl/commands/authentication
  - 78, https://docs.fireworks.ai/tools-sdks/firectl/commands/list-models
  - 79, https://docs.fireworks.ai/tools-sdks/firectl/commands/create-deployment
  - 80, https://docs.fireworks.ai/tools-sdks/firectl/commands/create-finetune-job
  - 81, https://docs.fireworks.ai/tools-sdks/firectl/commands/create-dataset
  - 82, https://docs.fireworks.ai/tools-sdks/firectl/commands/create-model
  - 83, https://docs.fireworks.ai/tools-sdks/firectl/commands/delete-model
  - 84, https://docs.fireworks.ai/tools-sdks/firectl/commands/deploy-model
  - 85, https://docs.fireworks.ai/tools-sdks/firectl/commands/download-model
  - 86, https://docs.fireworks.ai/tools-sdks/firectl/commands/get-model
  - 87, https://docs.fireworks.ai/tools-sdks/firectl/commands/import-model
  - 88, https://docs.fireworks.ai/tools-sdks/firectl/commands/undeploy-model
  - 89, https://docs.fireworks.ai/tools-sdks/python-client/installation
  - 90, https://docs.fireworks.ai/tools-sdks/python-client/api-reference
  - 91, https://docs.fireworks.ai/tools-sdks/openai-compatibility
