urls:
  - 001, https://fennel.ai/docs
  - 002, https://fennel.ai/docs/getting-started/installation
  - 003, https://fennel.ai/docs/getting-started/quickstart
  - 004, https://fennel.ai/docs/concepts/introduction
  - 005, https://fennel.ai/docs/concepts/source
  - 006, https://fennel.ai/docs/concepts/dataset
  - 007, https://fennel.ai/docs/concepts/pipeline
  - 008, https://fennel.ai/docs/concepts/sink
  - 009, https://fennel.ai/docs/concepts/featureset
  - 010, https://fennel.ai/docs/concepts/branch
  - 011, https://fennel.ai/docs/architecture/overview
  - 012, https://fennel.ai/docs/architecture/core-engine
  - 013, https://fennel.ai/docs/architecture/storage-model
  - 014, https://fennel.ai/docs/architecture/key-ideas
  - 015, https://fennel.ai/docs/architecture/read-write-separation
  - 016, https://fennel.ai/docs/architecture/technologies
  - 017, https://fennel.ai/docs/architecture/cost-optimizations
  - 018, https://fennel.ai/docs/data-quality/strong-typing
  - 019, https://fennel.ai/docs/data-quality/immutability-versioning
  - 020, https://fennel.ai/docs/data-quality/lineage-validation
  - 021, https://fennel.ai/docs/data-quality/metaflags
  - 022, https://fennel.ai/docs/data-quality/data-expectations
  - 023, https://fennel.ai/docs/data-quality/feature-drift
  - 024, https://fennel.ai/docs/development/unit-testing
  - 025, https://fennel.ai/docs/development/ci-cd-workflows
  - 026, https://fennel.ai/docs/development/console
  - 027, https://fennel.ai/docs/observability/metrics
  - 028, https://fennel.ai/docs/observability/grafana
  - 029, https://fennel.ai/docs/observability/datadog
  - 030, https://fennel.ai/docs/observability/newrelic
  - 031, https://fennel.ai/docs/observability/alerting
  - 032, https://fennel.ai/docs/observability/lineage
  - 033, https://fennel.ai/docs/observability/inspection
  - 034, https://fennel.ai/docs/security-compliance/overview
  - 035, https://fennel.ai/docs/security-compliance/deployment-model
  - 036, https://fennel.ai/docs/security-compliance/rbac
  - 037, https://fennel.ai/docs/security-compliance/sso
  - 038, https://fennel.ai/docs/security-compliance/scim
  - 039, https://fennel.ai/docs/useful-tips/code-organization
  - 040, https://fennel.ai/docs/useful-tips/python-environment
  - 041, https://fennel.ai/docs/useful-tips/troubleshooting
  - 042, https://fennel.ai/docs/api-reference/client/commit
  - 043, https://fennel.ai/docs/api-reference/client/log
  - 044, https://fennel.ai/docs/api-reference/client/query
  - 045, https://fennel.ai/docs/api-reference/client/query-offline
  - 046, https://fennel.ai/docs/api-reference/client/track-offline-query
  - 047, https://fennel.ai/docs/api-reference/client/cancel-offline-query
  - 048, https://fennel.ai/docs/api-reference/client/lookup
  - 049, https://fennel.ai/docs/api-reference/client/init-branch
  - 050, https://fennel.ai/docs/api-reference/client/clone-branch
  - 051, https://fennel.ai/docs/api-reference/client/delete-branch
  - 052, https://fennel.ai/docs/api-reference/client/checkout
  - 053, https://fennel.ai/docs/api-reference/client/branch
  - 054, https://fennel.ai/docs/api-reference/client/erase
  - 055, https://fennel.ai/docs/api-reference/rest-api/query  
  - 056, https://fennel.ai/docs/api-reference/rest-api/log
  - 057, https://fennel.ai/docs/api-reference/data-types/core-types
  - 058, https://fennel.ai/docs/api-reference/data-types/type-restrictions
  - 059, https://fennel.ai/docs/api-reference/data-types/duration
  - 060, https://fennel.ai/docs/api-reference/operators/aggregate
  - 061, https://fennel.ai/docs/api-reference/operators/assign
  - 062, https://fennel.ai/docs/api-reference/operators/changelog
  - 063, https://fennel.ai/docs/api-reference/operators/dedup
  - 064, https://fennel.ai/docs/api-reference/operators/drop
  - 065, https://fennel.ai/docs/api-reference/operators/dropnull
  - 066, https://fennel.ai/docs/api-reference/operators/explode
  - 067, https://fennel.ai/docs/api-reference/operators/filter
  - 068, https://fennel.ai/docs/api-reference/operators/first
  - 069, https://fennel.ai/docs/api-reference/operators/groupby
  - 070, https://fennel.ai/docs/api-reference/operators/join
  - 071, https://fennel.ai/docs/api-reference/operators/rename
  - 072, https://fennel.ai/docs/api-reference/operators/select
  - 073, https://fennel.ai/docs/api-reference/operators/transform
  - 074, https://fennel.ai/docs/api-reference/operators/union
  - 075, https://fennel.ai/docs/api-reference/source_connectors/avro
  - 076, https://fennel.ai/docs/api-reference/source_connectors/protobuf
  - 077, https://fennel.ai/docs/api-reference/source_connectors/bigquery
  - 078, https://fennel.ai/docs/api-reference/source_connectors/hudi
  - 079, https://fennel.ai/docs/api-reference/source_connectors/kafka
  - 080, https://fennel.ai/docs/api-reference/source_connectors/kinesis
  - 081, https://fennel.ai/docs/api-reference/source_connectors/mongo
  - 082, https://fennel.ai/docs/api-reference/source_connectors/mysql
  - 083, https://fennel.ai/docs/api-reference/source_connectors/postgres
  - 084, https://fennel.ai/docs/api-reference/source_connectors/pubsub
  - 085, https://fennel.ai/docs/api-reference/source_connectors/redshift
  - 086, https://fennel.ai/docs/api-reference/source_connectors/s3
  - 087, https://fennel.ai/docs/api-reference/source_connectors/secret
  - 088, https://fennel.ai/docs/api-reference/source_connectors/snowflake
  - 089, https://fennel.ai/docs/api-reference/source_connectors/webhook
  - 090, https://fennel.ai/docs/api-reference/sink_connectors/certificate
  - 091, https://fennel.ai/docs/api-reference/sink_connectors/http
  - 092, https://fennel.ai/docs/api-reference/sink_connectors/kafka
  - 093, https://fennel.ai/docs/api-reference/sink_connectors/s3
  - 094, https://fennel.ai/docs/api-reference/sink_connectors/snowflake
  - 095, https://fennel.ai/docs/api-reference/aggregations/average
  - 096, https://fennel.ai/docs/api-reference/aggregations/count
  - 097, https://fennel.ai/docs/api-reference/aggregations/distinct
  - 098, https://fennel.ai/docs/api-reference/aggregations/lastk
  - 099, https://fennel.ai/docs/api-reference/aggregations/firstk
  - 100, https://fennel.ai/docs/api-reference/aggregations/max
  - 101, https://fennel.ai/docs/api-reference/aggregations/min
  - 102, https://fennel.ai/docs/api-reference/aggregations/stddev
  - 103, https://fennel.ai/docs/api-reference/aggregations/sum
  - 104, https://fennel.ai/docs/api-reference/aggregations/quantile
  - 105, https://fennel.ai/docs/api-reference/aggregations/exponential-decay-sum
  - 106, https://fennel.ai/docs/api-reference/expressions/binary
  - 107, https://fennel.ai/docs/api-reference/expressions/col
  - 108, https://fennel.ai/docs/api-reference/expressions/datetime
  - 109, https://fennel.ai/docs/api-reference/expressions/eval
  - 110, https://fennel.ai/docs/api-reference/expressions/from_epoch
  - 111, https://fennel.ai/docs/api-reference/expressions/isnull
  - 112, https://fennel.ai/docs/api-reference/expressions/fillnull
  - 113, https://fennel.ai/docs/api-reference/expressions/not
  - 114, https://fennel.ai/docs/api-reference/expressions/typeof
  - 115, https://fennel.ai/docs/api-reference/expressions/when
  - 116, https://fennel.ai/docs/api-reference/expressions/dt/day
  - 117, https://fennel.ai/docs/api-reference/expressions/dt/hour
  - 118, https://fennel.ai/docs/api-reference/expressions/dt/minute
  - 119, https://fennel.ai/docs/api-reference/expressions/dt/month
  - 120, https://fennel.ai/docs/api-reference/expressions/dt/second
  - 121, https://fennel.ai/docs/api-reference/expressions/dt/since
  - 122, https://fennel.ai/docs/api-reference/expressions/dt/since_epoch
  - 123, https://fennel.ai/docs/api-reference/expressions/dt/strftime
  - 124, https://fennel.ai/docs/api-reference/expressions/dt/year
  - 125, https://fennel.ai/docs/api-reference/expressions/list/any
  - 126, https://fennel.ai/docs/api-reference/expressions/list/at
  - 127, https://fennel.ai/docs/api-reference/expressions/list/contains
  - 128, https://fennel.ai/docs/api-reference/expressions/list/filter
  - 129, https://fennel.ai/docs/api-reference/expressions/list/len
  - 130, https://fennel.ai/docs/api-reference/expressions/list/map
  - 131, https://fennel.ai/docs/api-reference/expressions/list/mean
  - 132, https://fennel.ai/docs/api-reference/expressions/list/sum
  - 133, https://fennel.ai/docs/api-reference/expressions/num/abs
  - 134, https://fennel.ai/docs/api-reference/expressions/num/ceil
  - 135, https://fennel.ai/docs/api-reference/expressions/num/floor
  - 136, https://fennel.ai/docs/api-reference/expressions/num/round
  - 137, https://fennel.ai/docs/api-reference/expressions/str/concat
  - 138, https://fennel.ai/docs/api-reference/expressions/str/concat
  - 139, https://fennel.ai/docs/api-reference/expressions/str/contains
  - 140, https://fennel.ai/docs/api-reference/expressions/str/endswith
  - 141, https://fennel.ai/docs/api-reference/expressions/str/json_extract
  - 142, https://fennel.ai/docs/api-reference/expressions/str/len
  - 143, https://fennel.ai/docs/api-reference/expressions/str/lower
  - 144, https://fennel.ai/docs/api-reference/expressions/str/parse
  - 145, https://fennel.ai/docs/api-reference/expressions/str/split
  - 146, https://fennel.ai/docs/api-reference/expressions/str/startswith
  - 147, https://fennel.ai/docs/api-reference/expressions/str/strptime
  - 148, https://fennel.ai/docs/api-reference/expressions/str/upper
  - 149, https://fennel.ai/docs/api-reference/expressions/struct/get
  - 150, https://fennel.ai/docs/api-reference/decorators/source
  - 151, https://fennel.ai/docs/api-reference/decorators/sink
  - 152, https://fennel.ai/docs/api-reference/expectations



